In [4]:
import numpy as np
#addition
ad=np.array([(1,2,3,4),(3,4,5,6)])
ad1=np.array([(1,2,3,4),(3,4,5,6)])
print(ad+ad1)

[[ 2  4  6  8]
 [ 6  8 10 12]]


In [5]:
import numpy as np

In [7]:
#subtraction
print(ad-ad1)

[[0 0 0 0]
 [0 0 0 0]]


In [8]:
#mulitiplication
print(ad*ad1)

[[ 1  4  9 16]
 [ 9 16 25 36]]


In [9]:
#divison
print(ad/ad1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
#concat
#vertical stacking
print(np.vstack((ad,ad1)))

[[1 2 3 4]
 [3 4 5 6]
 [1 2 3 4]
 [3 4 5 6]]


In [11]:
#horizontal stacking
print(np.hstack((ad,ad1)))

[[1 2 3 4 1 2 3 4]
 [3 4 5 6 3 4 5 6]]


In [13]:
#to make a single column
print(ad.ravel())

[1 2 3 4 3 4 5 6]


In [15]:
ls=np.linspace(1,3,5)
print(ls)
ls1=np.linspace(1,5,10)
print(ls1)

[1.  1.5 2.  2.5 3. ]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [16]:
m1=np.array([1,2,3])
print(m1.max())
print(m1.min())
print(m1.sum())

3
1
6


In [17]:
ar3=np.array([(1,2,3,4),(3,4,5,6)])
print(ar3)
print(ar3.sum(axis=0))
print(ar3.sum(axis=1))

[[1 2 3 4]
 [3 4 5 6]]
[ 4  6  8 10]
[10 18]


In [18]:
print(np.sqrt(ar3))

[[1.         1.41421356 1.73205081 2.        ]
 [1.73205081 2.         2.23606798 2.44948974]]


In [20]:
print(np.std(ar3))

1.5


In [27]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [22]:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [23]:
print(a.ndim)

2


In [26]:
a=np.array([1,2,3])
print(a.ndim)

1


In [28]:
print(a.itemsize)

4


In [30]:
print(a.dtype)

int32


In [32]:
n=np.array([(1,2,3),(2,3,4)])
p=np.array([1,2,3])
print(n.size)
print(p.size)
n.nbytes
p.nbytes

6
3


12

In [33]:
print(n.shape)
print(n)

(2, 3)
[[1 2 3]
 [2 3 4]]


In [34]:
ar=np.array([(1,2,3,4),(3,4,5,6)])
ar=ar.reshape(4,2)
print(ar)

[[1 2]
 [3 4]
 [3 4]
 [5 6]]


In [35]:
ar1=np.array([(1,2,3,4),(3,4,5,6)])
print(ar1)
print(ar1[0,1])

[[1 2 3 4]
 [3 4 5 6]]
2


In [36]:
import numpy as np

# create a list named list1
list1 = [2, 4, 6, 8]

# create numpy array using list1
array1 = np.array(list1)

print(array1)

[2 4 6 8]
